[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_ENABLED = "false"

# Desactivar prerendering heredado
[context.production]
  [context.production.environment]
    NETLIFY_ENABLE_PRERENDER = "false"

# Configuración para SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
